# JanNaadi — one image, two roles, picked via APP_ROLE env:
#   web    (default): Next.js standalone server            → Cloud Run 'jannaadi'
#   worker: tsx worker/ingest.ts (Pub/Sub consumer)        → Cloud Run 'jannaadi-worker'
# Monorepo note: outputFileTracingRoot is the repo root, so the standalone server
# lands at .next/standalone/apps/web/server.js (CMD reflects that, not ./server.js).
FROM node:20-alpine AS base

# Stage 1: Install dependencies
FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json package-lock.json ./
COPY apps/web/package.json apps/web/package.json
RUN npm ci

# Stage 2: Build the application
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
# Generates the optimized .next/standalone directory (apps/web/next.config.ts)
RUN npm run build
# Worker role runs from source via tsx — keep only production deps for the runtime copy
RUN npm prune --omit=dev

# Stage 3: Production server
FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production
# Cloud Run expects the app to listen on PORT 8080 by default
ENV PORT=8080
ENV HOSTNAME=0.0.0.0
EXPOSE 8080

# Security best practice: Run as non-root user
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Standalone build output (web role). No public/ dir in this app — API routes only.
COPY --from=builder --chown=nextjs:nodejs /app/apps/web/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/apps/web/.next/static ./apps/web/.next/static
# /api/rank reads api/rank.sql at runtime (resolved ../../api from the server cwd)
COPY --from=builder --chown=nextjs:nodejs /app/api ./api
# Worker role: sources + pruned prod node_modules (tsx is a prod dep; overwrites the
# thinner traced node_modules from the standalone copy above — full set is a superset)
COPY --from=builder --chown=nextjs:nodejs /app/worker ./worker
COPY --from=builder --chown=nextjs:nodejs /app/node_modules ./node_modules
COPY --from=builder --chown=nextjs:nodejs /app/package.json ./package.json

USER nextjs

# Start the minimal server generated by standalone mode (or the worker)
CMD ["sh", "-c", "if [ \"$APP_ROLE\" = worker ]; then exec node_modules/.bin/tsx worker/ingest.ts; else exec node apps/web/server.js; fi"]
