// data/generate.ts — JanNaadi synthetic citizen submissions
// T1 LLM-grounded generator. Output: data/synthetic.jsonl + data/synthetic_inserts.sql
// Run with API key:   GEMINI_API_KEY=... npx tsx data/generate.ts
// Run with Vertex AI: USE_VERTEX=1 npx tsx data/generate.ts  (uses ADC + jannaadi project)
// Cost control: batched Gemini calls (25 items/call), ~32 calls total.

import { GoogleGenAI, Type } from "@google/genai";
import { writeFileSync, appendFileSync, existsSync, unlinkSync } from "fs";
import { randomUUID } from "crypto";

const useVertex = !!process.env.USE_VERTEX;
const ai = useVertex
  ? new GoogleGenAI({ vertexai: true, project: process.env.GCP_PROJECT ?? "jannaadi", location: "us-central1" })
  : new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY! });
if (useVertex) console.log("🔑 Using Vertex AI (ADC) — project jannaadi us-central1");
else console.log("🔑 Using Gemini API key");
const MODEL = "gemini-2.5-flash";        // generation model; extraction pipeline pins -002
const TOTAL = 800;
const BATCH = 25;

// ── Distributions (spec from build plan) ──────────────────
// Wards: single source of truth is data/wards_clean.json (mirrors db/seed.sql,
// both generated by scripts/clean-wards.ts from the official GVMC 98-ward scrape).
import wardsClean from "./wards_clean.json";
const WARDS: Record<string, { lat: number; lng: number }> = Object.fromEntries(
  (wardsClean as { name: string; lat: number; lng: number }[]).map((w) => [w.name, { lat: w.lat, lng: w.lng }])
);

// lang: 45% te, 30% hi, 25% en; 15% of each rendered code-mixed
const LANGS = weighted([["te", 0.45], ["hi", 0.30], ["en", 0.25]]);
// channel: 60% text, 25% voice(-transcript style), 15% photo+caption
const CHANNELS = weighted([["text", 0.60], ["voice", 0.25], ["photo", 0.15]]);
// category base rates — calibrated from REAL GVMC 2026 data (7,162 complaints)
// Source: GVMC e-Governance Citizen Grievance Zone & Department Report, Year 2026
// garbage:PH-Sanitation(1639), roads:Eng-PW+AGI-PW+PL&C+Upit(1596),
// streetlights:Eng-Electrical(1214), water:Eng-WaterSupply(829),
// health:PH-depts(~574), drainage:Eng-UGD(430), other+education: residual
const CATEGORIES = weighted([
  ["garbage",      0.23],  // 1639/7162 — PH-Sanitation (was 0.12 — doubled)
  ["roads",        0.22],  // 1596/7162 — Eng-PW + AGI-PW + PL&C + Upit (was 0.30)
  ["streetlights", 0.17],  // 1214/7162 — Eng-Electrical (was 0.05 — 3× increase)
  ["water",        0.12],  // 829/7162  — Eng-Water Supply (was 0.20)
  ["health",       0.08],  // ~574/7162 — PH depts combined (was 0.15)
  ["drainage",     0.06],  // 430/7162  — Eng-UGD ✓ unchanged
  ["other",        0.08],  // ~490/7162 — Town Planning, Revenue, GVMC-IT
  ["education",    0.04],  // minimal in GVMC data; retained for demo golden-set variety
]);

// ── Hotspot injection: clusters the pipeline MUST find (B2) ──
// Overrides category+ward for a slice of rows so demand visibly concentrates.
const HOTSPOTS = [
  { ward: "Ward 75 - Pedagantyada",          category: "drainage",     count: 60 }, // Gajuwaka-area, top-5 guarantee (B2)
  { ward: "Ward 96 - Pendurthi old Village", category: "health",       count: 40 }, // PHC theme, demo beat G04
  { ward: "Ward 25 - Madhura Nagar",         category: "water",        count: 35 },
  { ward: "Ward 8 - Law College",            category: "streetlights", count: 25 },
];
// Guard: hotspot wards must exist in the ward list (loud, never silent)
for (const h of HOTSPOTS) if (!WARDS[h.ward]) throw new Error(`hotspot ward not in wards_clean.json: ${h.ward}`);

// ── Gemini batch prompt: realistic citizen voices ─────────
const geminiSchema = {
  type: Type.ARRAY,
  items: {
    type: Type.OBJECT,
    properties: {
      raw_text: { type: Type.STRING }, // the citizen's own words, native script
      severity: { type: Type.INTEGER }, // 1–5, generator's ground-truth label
    },
    required: ["raw_text", "severity"],
  },
};

async function generateBatch(specs: RowSpec[]): Promise<{ raw_text: string; severity: number }[]> {
  const lines = specs.map((s, i) =>
    `${i + 1}. lang=${s.lang}${s.mixed ? " (code-mixed with English, natural Tenglish/Hinglish)" : ""}, ` +
    `channel=${s.channel}${s.channel === "voice" ? " (spoken register: fillers, informal)" : ""}` +
    `${s.channel === "photo" ? " (short caption for an uploaded photo)" : ""}, ` +
    `category=${s.category}, ward=${s.ward}`
  ).join("\n");

  const res = await ai.models.generateContent({
    model: MODEL,
    contents:
      `Generate ${specs.length} realistic citizen complaints/development requests from Visakhapatnam, India. ` +
      `Vary length (10–80 words), tone (frustrated, polite, urgent), and specificity (some name streets/landmarks, some vague). ` +
      `Telugu in Telugu script, Hindi in Devanagari. Code-mixed = script-mixed, how real people type on WhatsApp. ` +
      `NEVER mention the category or ward name mechanically; embed naturally. Include severity 1–5 (5 = safety risk).\n\n${lines}`,
    config: { responseMimeType: "application/json", responseSchema: geminiSchema, temperature: 1.0 },
  });
  const parsed = JSON.parse(res.text!);
  if (!Array.isArray(parsed) || parsed.length !== specs.length)
    throw new Error(`batch size mismatch: got ${parsed?.length}, want ${specs.length}`); // loud, never silent
  return parsed;
}

// ── Row spec assembly ──────────────────────────────────────
type RowSpec = { lang: string; mixed: boolean; channel: string; category: string; ward: string };

function buildSpecs(): RowSpec[] {
  const specs: RowSpec[] = [];
  // 1. hotspot rows first (fixed ward+category)
  for (const h of HOTSPOTS)
    for (let i = 0; i < h.count; i++)
      specs.push({ lang: pick(LANGS), mixed: Math.random() < 0.15, channel: pick(CHANNELS), category: h.category, ward: h.ward });
  // 2. background noise fills the rest
  const wardNames = Object.keys(WARDS);
  while (specs.length < TOTAL)
    specs.push({
      lang: pick(LANGS), mixed: Math.random() < 0.15, channel: pick(CHANNELS),
      category: pick(CATEGORIES), ward: wardNames[Math.floor(Math.random() * wardNames.length)],
    });
  return shuffle(specs);
}

// ── Timestamp skew: last 90 days, recency-weighted ─────────
function skewedTimestamp(): number {
  const days = Math.floor(90 * Math.pow(Math.random(), 2)); // quadratic → recent bias
  return days;
}

// ── Resolution status: older complaints more likely resolved ──
// Bug fix (10 Jul): this generator predates db/trust_and_feedback.sql's
// resolution_status column, so every synthetic row defaulted to 'open' —
// the demo dashboard had zero resolved/in-progress data to show. Mirrors
// scripts/seed-resolution-status.ts, which backfilled the already-frozen
// demo_seed.dump; kept here too so future regenerations aren't affected.
function resolutionStatusForAge(ageDays: number): string {
  const r = Math.random();
  const buckets: [string, number][] =
    ageDays > 60 ? [["resolved", 0.70], ["in_progress", 0.20], ["acknowledged", 0.05], ["open", 0.05]] :
    ageDays > 30 ? [["resolved", 0.40], ["in_progress", 0.30], ["acknowledged", 0.15], ["open", 0.15]] :
    ageDays > 7  ? [["resolved", 0.15], ["in_progress", 0.30], ["acknowledged", 0.25], ["open", 0.30]] :
                   [["resolved", 0.05], ["in_progress", 0.10], ["acknowledged", 0.15], ["open", 0.70]];
  let acc = 0;
  for (const [status, p] of buckets) { acc += p; if (r < acc) return status; }
  return "open";
}

// ── Geo jitter around ward centroid (~1.5km) ───────────────
const jitter = () => (Math.random() - 0.5) * 0.027;

// ── Main ───────────────────────────────────────────────────
async function main() {
  for (const f of ["data/synthetic.jsonl", "data/synthetic_inserts.sql"])
    if (existsSync(f)) unlinkSync(f);
  writeFileSync("data/synthetic_inserts.sql",
    "-- Generated. Embeddings NULL here; ingest worker embeds on replay, OR run scripts/embed-seed.ts\n");

  const specs = buildSpecs();
  for (let i = 0; i < specs.length; i += BATCH) {
    const slice = specs.slice(i, i + BATCH);
    const texts = await retry(() => generateBatch(slice), 2); // retry batch once, then fail loud
    slice.forEach((s, j) => {
      const w = WARDS[s.ward];
      const ageDays = skewedTimestamp();
      const submittedAt = new Date(Date.now() - ageDays * 86400_000 - Math.random() * 86400_000).toISOString();
      const row = {
        id: randomUUID(),
        channel: s.channel,
        lang: s.mixed ? "mixed" : s.lang,
        raw_text: texts[j].raw_text,
        category: s.category,          // ground truth — worker re-extracts; diff = extraction QA signal
        ward: s.ward,
        severity: texts[j].severity,
        lat: w.lat + jitter(), lng: w.lng + jitter(),
        submitted_at: submittedAt,
        resolution_status: resolutionStatusForAge(ageDays),
        is_synthetic: true,
      };
      appendFileSync("data/synthetic.jsonl", JSON.stringify(row) + "\n");
      appendFileSync("data/synthetic_inserts.sql",
        `INSERT INTO submissions (id,channel,lang,raw_text,category,ward,severity,lat,lng,submitted_at,resolution_status,is_synthetic,status)` +
        ` VALUES ('${row.id}','${row.channel}','${row.lang}',${sqlStr(row.raw_text)},'${row.category}','${row.ward}',` +
        `${row.severity},${row.lat},${row.lng},'${row.submitted_at}','${row.resolution_status}',true,'received');\n`);
    });
    console.log(`batch ${i / BATCH + 1}/${Math.ceil(TOTAL / BATCH)} done`);
  }
  console.log(`✓ ${TOTAL} rows → synthetic.jsonl + synthetic_inserts.sql`);
  console.log("Next: psql -f data/synthetic_inserts.sql, then run worker in replay mode to embed+cluster, then pg_dump demo snapshot.");
}

// ── Helpers ────────────────────────────────────────────────
function weighted(pairs: [string, number][]): string[] {
  return pairs.flatMap(([v, p]) => Array(Math.round(p * 100)).fill(v));
}
const pick = (arr: string[]) => arr[Math.floor(Math.random() * arr.length)];
function shuffle<T>(a: T[]): T[] {
  for (let i = a.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [a[i], a[j]] = [a[j], a[i]]; }
  return a;
}
const sqlStr = (s: string) => `'${s.replace(/'/g, "''")}'`;
async function sleep(ms: number) { return new Promise(r => setTimeout(r, ms)); }
async function retry<T>(fn: () => Promise<T>, n: number): Promise<T> {
  for (let i = 0; ; i++) {
    try { return await fn(); }
    catch (e) { if (i >= n) throw e; console.warn(`retry ${i + 1}: ${e}`); await sleep(4000 * (i + 1)); }
  }
}

main();
