// scripts/build-plan-sources.ts — real Vizag plan/infrastructure documents →
// db/plan_documents.sql (table + rows), from the Teamwork swarm's source data:
//   data/source_data/pib_press_releases.json      (govt announcements, ward-tagged)
//   data/source_data/pppinindia_infrastructure.json (PPP projects, geo-tagged)
// The worker's LOCAL plan-match fallback (worker/planmatch.ts) scores clusters
// against this table when no Discovery Engine datastore is configured (T3/B15).
// Run: npx tsx scripts/build-plan-sources.ts   then: psql -f db/plan_documents.sql
import { readFileSync, writeFileSync } from "fs";
import path from "path";

const ROOT = path.resolve(__dirname, "..");
const esc = (s: string) => s.replace(/'/g, "''");
const arr = (a: string[]) => `ARRAY[${a.map((x) => `'${esc(x)}'`).join(",")}]::text[]`;

type Doc = { id: string; source: string; doc_title: string; body: string; sectors: string[]; wards: string[]; lat: number | null; lng: number | null; status: string | null; published_at: string | null };
const docs: Doc[] = [];

const pib = JSON.parse(readFileSync(path.join(ROOT, "data", "source_data", "pib_press_releases.json"), "utf8"));
for (const r of pib.press_releases) {
  docs.push({
    id: r.release_id, source: "PIB press release",
    doc_title: r.headline, body: r.text,
    sectors: r.associated_sectors ?? [], wards: r.impacted_wards ?? [],
    lat: null, lng: null, status: null, published_at: r.date ?? null,
  });
}

const ppp = JSON.parse(readFileSync(path.join(ROOT, "data", "source_data", "pppinindia_infrastructure.json"), "utf8"));
for (const p of ppp.projects) {
  docs.push({
    id: p.project_id, source: "PPP India infrastructure project",
    doc_title: p.project_name,
    body: `${p.description ?? ""} Authority: ${p.authority ?? "-"}. Partner: ${p.private_partner ?? "-"}. Cost: ₹${p.project_cost_inr_cr ?? "?"} Cr. Mode: ${p.ppp_mode ?? "-"}.`,
    sectors: [p.sector, p.sub_sector].filter(Boolean), wards: [],
    lat: p.coordinates?.lat ?? null, lng: p.coordinates?.lng ?? null,
    status: p.status ?? null, published_at: p.concession_signing_date ?? null,
  });
}

if (!docs.length) throw new Error("no plan documents built — check data/source_data/");

const sql =
  `-- Generated by scripts/build-plan-sources.ts from data/source_data/ (real Vizag data).\n` +
  `-- Local plan-match corpus (T3/B15 fallback when PLAN_DATASTORE_ID is not configured).\n\n` +
  `CREATE TABLE IF NOT EXISTS plan_documents (\n` +
  `  id           TEXT PRIMARY KEY,\n` +
  `  source       TEXT NOT NULL,\n` +
  `  doc_title    TEXT NOT NULL,\n` +
  `  body         TEXT NOT NULL,\n` +
  `  sectors      TEXT[] NOT NULL DEFAULT '{}',\n` +
  `  wards        TEXT[] NOT NULL DEFAULT '{}',   -- ward names per wards.name, when tagged\n` +
  `  lat          DOUBLE PRECISION,\n` +
  `  lng          DOUBLE PRECISION,\n` +
  `  status       TEXT,\n` +
  `  published_at TIMESTAMPTZ\n` +
  `);\n\n` +
  `INSERT INTO plan_documents (id, source, doc_title, body, sectors, wards, lat, lng, status, published_at) VALUES\n` +
  docs.map((d) =>
    `  ('${esc(d.id)}', '${esc(d.source)}', '${esc(d.doc_title)}', '${esc(d.body)}', ${arr(d.sectors)}, ${arr(d.wards)}, ` +
    `${d.lat ?? "NULL"}, ${d.lng ?? "NULL"}, ${d.status ? `'${esc(d.status)}'` : "NULL"}, ${d.published_at ? `'${esc(d.published_at)}'` : "NULL"})`
  ).join(",\n") +
  `\nON CONFLICT (id) DO UPDATE SET source=EXCLUDED.source, doc_title=EXCLUDED.doc_title, body=EXCLUDED.body,\n` +
  `  sectors=EXCLUDED.sectors, wards=EXCLUDED.wards, lat=EXCLUDED.lat, lng=EXCLUDED.lng,\n` +
  `  status=EXCLUDED.status, published_at=EXCLUDED.published_at;\n`;
// (no web-role grant needed: only the worker — table owner — reads plan_documents)

writeFileSync(path.join(ROOT, "db", "plan_documents.sql"), sql);
console.log(`✓ ${docs.length} plan documents → db/plan_documents.sql`);
