// scripts/clean-wards.ts — canonicalize the GVMC 98-ward scrape (decision: real
// 98 wards replace the 12 placeholders; discrepancies cleaned here).
// Input:  data/gvmc_wards.json  (frontend agent's scrape — source of truth)
// Output: data/wards_clean.json (canonical list for generate.ts + docs)
//         data/wards_real.sql   (clean INSERT block, standalone-appliable)
//         db/seed.sql           (ward INSERT block replaced in place)
// Cleaning rules:
//  - collapse embedded newlines/whitespace in names (wards 68, 82)
//  - Ward 44 has no name on the official page → 'Ward 44 - (name pending)';
//    human fills the official name when known (flagged loudly)
//  - demo_weight left at 1.000 default: db/ward_population.sql applies official
//    SC+ST-based weights by ward_number afterwards. NOTE: that census file uses
//    the 72-ward scheme vs this 98-ward scheme — human must confirm the mapping.
//  - ward_number INTEGER column (already in schema), set in the INSERT
// Run: npx tsx scripts/clean-wards.ts
import { readFileSync, writeFileSync } from "fs";
import path from "path";

const ROOT = path.resolve(__dirname, "..");
const raw: { wardNo: number; name: string; approx_lat: number; approx_lng: number; population: number }[] =
  JSON.parse(readFileSync(path.join(ROOT, "data", "gvmc_wards.json"), "utf8"));

if (raw.length !== 98) throw new Error(`expected 98 wards, got ${raw.length}`);

// Name overrides where the source page itself is defective. Ward 44's locality
// list begins with a stray comma on gvmc.gov.in; official first locality confirmed
// from the GVMC AreaWards PDF (wards.pdf p17): Santoshi Matha Temple.
const NAME_OVERRIDES: Record<number, string> = { 44: "Santoshi Matha Temple" };

// Real SC/ST-based demo_weight where official ward-mapped demographics exist
// (data/source_data/gpdp_demographics.json, keyed by our exact ward names).
// Formula matches db/ward_population.sql: 0.80 + (sc% + st%)/27.16 * 0.50.
// Wards without mapped demographics stay at 1.000 (tunable live via rank_weights, B10).
let GPDP: Record<string, number> = {};
try {
  const g = JSON.parse(readFileSync(path.join(ROOT, "data", "source_data", "gpdp_demographics.json"), "utf8"));
  for (const r of g.records ?? []) {
    const sv = r.demographics?.social_vulnerabilities;
    if (r.mapped_gvmc_ward && sv?.sc_percentage != null && sv?.st_percentage != null)
      GPDP[r.mapped_gvmc_ward] = Number((0.8 + ((sv.sc_percentage + sv.st_percentage) / 27.16) * 0.5).toFixed(3));
  }
  console.log(`gpdp demographics: real demo_weight for ${Object.keys(GPDP).length} wards`);
} catch (e) {
  console.warn(`gpdp_demographics.json not usable (${e}) — all demo_weights stay 1.000`);
}

const clean = raw
  .map((w) => {
    let name = w.name.replace(/\s+/g, " ").replace(/&(?=\S)/g, "& ").trim();
    if (NAME_OVERRIDES[w.wardNo]) name = `Ward ${w.wardNo} - ${NAME_OVERRIDES[w.wardNo]}`;
    else if (/-\s*$/.test(name)) {
      name = `Ward ${w.wardNo} - (name pending)`;
      console.warn(`⚠ Ward ${w.wardNo}: official name missing on source page — placeholder used, human to fill`);
    }
    return {
      ward_number: w.wardNo,
      name,
      lat: w.approx_lat,
      lng: w.approx_lng,
      population: w.population,
      demo_weight: GPDP[name] ?? 1.0,
    };
  })
  .sort((a, b) => a.ward_number - b.ward_number);

const dupNames = clean.map((w) => w.name).filter((n, i, a) => a.indexOf(n) !== i);
if (dupNames.length) throw new Error(`duplicate ward PK names after cleaning: ${dupNames.join(", ")}`);

// 1. canonical JSON
writeFileSync(path.join(ROOT, "data", "wards_clean.json"), JSON.stringify(clean, null, 2) + "\n");

// 2. INSERT block (shared by wards_real.sql and seed.sql)
const esc = (s: string) => s.replace(/'/g, "''");
const insertBlock =
  `INSERT INTO wards (name, ward_number, lat, lng, population, demo_weight) VALUES\n` +
  clean.map((w) => `  ('${esc(w.name)}', ${w.ward_number}, ${w.lat}, ${w.lng}, ${w.population}, ${w.demo_weight})`).join(",\n") +
  ";\n";

writeFileSync(
  path.join(ROOT, "data", "wards_real.sql"),
  `-- Generated by scripts/clean-wards.ts from data/gvmc_wards.json (official GVMC 98 wards).\n` +
    `-- Same block lives in db/seed.sql (single source of truth, swapped together).\n` +
    `-- Ward 44's official name is missing on the source page — placeholder '(name pending)'.\n\n` +
    insertBlock
);

// 3. splice into db/seed.sql: replace the ward INSERT block, keep everything else
const seedPath = path.join(ROOT, "db", "seed.sql");
const seed = readFileSync(seedPath, "utf8");
const re = /INSERT INTO wards \([^)]*\) VALUES\n(?:.*\n)*?.*?;\n/;
if (!re.test(seed)) throw new Error("could not locate the ward INSERT block in db/seed.sql");
let next = seed.replace(re, insertBlock);
if (!next.includes("ward_number")) throw new Error("seed.sql schema must declare ward_number before splicing");
writeFileSync(seedPath, next);

console.log(`✓ ${clean.length} wards → data/wards_clean.json, data/wards_real.sql, db/seed.sql`);
